//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por PIA PA FINAL.rc
//
#define IDD_INSESION                    101
#define IDD_INFOVENDEDOR                103
#define IDD_NUEVOPROD                   105
#define IDD_ELIMINARPROD                107
#define IDD_EDITPROD                    109
#define IDD_REALIZARENVI                110
#define IDD_EDITENVI                    111
#define IDD_MISENVI                     112
#define IDD_MISPROD                     117
#define IDD_CANCENVI                    119
#define IDD_REGISUSUA                   121
#define IDR_MENU1                       122
#define IDD_AGREGACLIENTE               124
#define IDD_EDITCLIEN                   126
#define IDD_REGISTROCLIENTE             128
#define IDD_ELIMINACLIENTE              130
#define IDD_AGREGATIENDA                132
#define IDD_REGISTROTIENDA              134
#define IDD_EDITTIENDA                  136
#define IDD_ELIMINATIENDA               137
#define IDD_AGREGACOMPRA                140
#define IDD_EDITCOMPRA                  141
#define IDD_VENTAPROD                   146
#define IDD_VENTATIENDA                 148
#define IDC_USUARIO                     1001
#define IDC_CONTRASENA                  1002
#define IDC_INICIAR_SESION              1003
#define IDC_REGISTRARSE                 1004
#define IDC_BTNREGISTRRAR               1005
#define IDC_BTNREGRESAR                 1006
#define IDC_NVUSUA                      1007
#define IDC_NVCONTRA                    1008
#define IDC_NMBCOMPLETO                 1009
#define IDC_ALIASEMPRESA                1010
#define IDC_BTNEDITARDATOS              1011
#define IDC_BTNGUARDARDATOS             1012
#define IDC_BTNFOTOIV                   1013
#define IDC_FOTOIV                      1014
#define IDC_STATICIV                    1015
#define IDC_LISTMP                      1016
#define IDC_BTNMPMP                     1017
#define IDC_BTNTLPMP                    1018
#define IDC_NMBPRODMP                   1019
#define IDC_CANTIDADMP                  1020
#define IDC_CODIGOMP                    1021
#define IDC_MARCAMP                     1022
#define IDC_PRECIOMP                    1023
#define IDC_DESCRIPCIONMP               1024
#define IDC_FOTOMP1                     1025
#define IDC_FOTOMP2                     1026
#define IDC_NMBPRNP                     1027
#define IDC_CINP                        1028
#define IDC_CPNP                        1029
#define IDC_MNP                         1030
#define IDC_PNP                         1031
#define IDC_DNP                         1032
#define IDC_BTNGRDNP                    1033
#define IDC_BTNFOTO1NP                  1034
#define IDC_BTNFOTO2NP                  1035
#define IDC_FOTO1NP                     1036
#define IDC_FOTO2NP                     1037
#define IDC_STATICNP                    1038
#define IDC_STATIC2NP                   1039
#define IDC_BTNBSCEP                    1040
#define IDC_BSCEP                       1041
#define IDC_NMBPRODEP                   1042
#define IDC_CIEP                        1043
#define IDC_CPEP                        1044
#define IDC_MEP                         1045
#define IDC_DEP                         1046
#define IDC_PEP                         1047
#define IDC_BTNFOTO1EP                  1048
#define IDC_BTNFOTO2EP                  1049
#define IDC_BTNGUARDAREP                1050
#define IDC_BTNCANCELAREP               1051
#define IDC_FOTO1EP                     1052
#define IDC_FOTO2EP                     1053
#define IDC_STATIC1EP                   1054
#define IDC_STATIC2EP                   1055
#define IDC_BTNBSCARELP                 1056
#define IDC_BSCRELP                     1057
#define IDC_NMBELP                      1058
#define IDC_CIELP                       1059
#define IDC_CPELP                       1060
#define IDC_MELP                        1061
#define IDC_DELP                        1062
#define IDC_PELP                        1063
#define IDC_BTNELPELP                   1064
#define IDC_BTNCNELP                    1065
#define IDC_FOTO1ELP                    1066
#define IDC_FOTO2ELP                    1067
#define IDC_LISTFECHAME                 1068
#define IDC_CALLEME                     1069
#define IDC_COLONIAME                   1070
#define IDC_CIUDADME                    1071
#define IDC_ESTADOME                    1072
#define IDC_PRODUCTOME                  1073
#define IDC_CANTIDADME                  1074
#define IDC_ESTATUSME                   1075
#define IDC_LISTPRRE                    1076
#define IDC_CIRE                        1077
#define IDC_CERE                        1078
#define IDC_CCRE                        1079
#define IDC_BTNCCRE                     1080
#define IDC_BTNGEEE                     1081
#define IDC_CALLERE                     1082
#define IDC_CIUDADRE                    1083
#define IDC_COLONIARE                   1084
#define IDC_ESTADORE                    1085
#define IDC_MENSAJERE                   1086
#define IDC_DATETIMEPICKER1             1087
#define IDC_BTNGUARE                    1088
#define IDC_LISTEE                      1089
#define IDC_CALLEEE                     1090
#define IDC_COLONIAEE                   1091
#define IDC_CIUDADEE                    1092
#define IDC_ESTADOEE                    1093
#define IDC_BTNCANEE                    1094
#define IDC_LISTFECHENCE                1095
#define IDC_PRODUCTEE                   1096
#define IDC_CANTIDADEE                  1097
#define IDC_PRODCE                      1098
#define IDC_CANTIDADCE                  1099
#define IDC_CALLECE                     1100
#define IDC_COLONIACE                   1101
#define IDC_CIUDADCE                    1102
#define IDC_ESTADOCE                    1103
#define IDC_CANCELARCE                  1104
#define IDC_FTUSUARIORE                 1105
#define IDC_FTUSUARIONP                 1106
#define IDC_FTUSUARIOMP                 1107
#define IDC_FTUSUARIOMI                 1108
#define IDC_FTUSUARIOME                 1109
#define IDC_FTUSUARIOEP                 1110
#define IDC_FTUSUARIOEDP                1111
#define IDC_FTUSUARIOEDE                1112
#define IDC_FTUSUARIOCE                 1113
#define IDC_USUACE                      1114
#define IDC_USUAEDE                     1115
#define IDC_USUAEDP                     1116
#define IDC_USUAEP                      1117
#define IDC_USUAME                      1118
#define IDC_USUAMP                      1119
#define IDC_USUANP                      1120
#define IDC_CANCCE                      1121
#define IDC_NOMCL                       1121
#define IDC_USUARE                      1122
#define IDC_IDCL                        1122
#define IDC_TELCL                       1123
#define IDC_ESTCL                       1124
#define IDC_BTNAGREGA                   1125
#define IDC_ENOMCL                      1127
#define IDC_EIDCL                       1128
#define IDC_ETELCL                      1129
#define IDC_EESTCL                      1130
#define IDC_EDATEREGCL                  1131
#define IDC_EBTNAGREGA                  1132
#define IDC_ListRegCl                   1133
#define IDC_BtnModCl                    1135
#define IDC_BtnEliCl                    1136
#define IDC_ELNOMCL                     1137
#define IDC_ELIDCL                      1138
#define IDC_ELTELCL                     1139
#define IDC_ELESTCL                     1140
#define IDC_ELDATEREGCL                 1141
#define IDC_ELBTNAGREGA                 1142
#define IDC_NomTien                     1143
#define IDC_CombEstTien                 1145
#define IDC_IDtien                      1146
#define IDC_BtnGuardTien                1147
#define IDC_IDdes                       1149
#define IDC_Teldes                      1150
#define IDC_Estatusdes                  1151
#define IDC_Fechdes                     1152
#define IDC_LIST1                       1153
#define IDC_EDIT1                       1154
#define IDC_EDIT2                       1155
#define IDC_EDIT3                       1156
#define IDC_EDIT4                       1157
#define IDC_BUTTON2                     1159
#define IDC_BUTTON3                     1160
#define IDC_CorreoTien                  1161
#define IDC_MNomTien                    1162
#define IDC_MIDtien                     1163
#define IDC_MCorreoTien                 1164
#define IDC_MCombEstTien                1165
#define IDC_MBtnGuardTien               1166
#define IDC_ENomTien                    1167
#define IDC_EIDtien                     1168
#define IDC_ECorreoTien                 1169
#define IDC_ECombEstTien                1170
#define IDC_EBtnGuardTien               1171
#define IDC_COMBO1                      1172
#define IDC_EditCosto                   1173
#define IDC_EditIDT                     1174
#define IDC_EditEstatus                 1175
#define IDC_ElCosto                     1176
#define IDC_ElIDT                       1177
#define IDC_ELCombEst                   1178
#define IDC_BUTTON1                     1179
#define IDC_BUTTON4                     1180
#define IDC_DATETIMEPICKER2             1181
#define IDC_LIST2                       1183
#define IDC_VENTAPROD                   1186
#define IDC_EDIT5                       1188
#define IDC_EDIT6                       1189
#define IDC_EDIT7                       1190
#define IDC_EDIT8                       1191
#define IDC_EDIT9                       1192
#define IDC_EDIT10                      1193
#define IDC_MApMa                       1194
#define IDC_MApPa                       1195
#define IDC_EApMa                       1196
#define IDC_EApPa                       1197
#define ID_INFORMACIONDELVENDEDOR_INFORMACION 40001
#define ID_INFORMACIONDELVENDEDOR       40002
#define ID_PRODUCTOS_MISPRODUCTOS       40003
#define ID_PRODUCTOS_NUEVOPRODUCTO      40004
#define ID_PRODUCTOS_EDITARPRODUCTO     40005
#define ID_PRODUCTOS_ELIMINARPRODUCTO   40006
#define ID_ENVIOS_MISENVIOS             40007
#define ID_ENVIOS_REALIZARENVIO         40008
#define ID_ENVIOS_EDITARENVIO           40009
#define ID_ENVIOS_CANCELARENVIO         40010
#define ID_SALIR                        40011
#define ID_SALIR_GUARDARYSALIR          40012
#define ID_SALIR_CERRARSESION           40013
#define ID_CLIENTE_AGREGAR              40014
#define ID_CLIENTE_MODIFICAR            40015
#define ID_CLIENTE_ELIMINAR             40016
#define ID_CLIENTE_LISTA                40017
#define ID_TIENDAS_AGREGAR              40018
#define ID_TIENDAS_MODIFICAR            40019
#define ID_TIENDAS_ELIMINAR             40020
#define ID_COMPRA                       40021
#define ID_COMPRA_REALIZAR              40022
#define ID_COMPRA_HISTORIAL             40023
#define ID_TIENDAS_LISTA                40024
#define ID_COMPRAS_EDITAR               40025
#define ID_REPORTE_VENTASPORPRODUCTO    40026
#define ID_REPORTE_VENTASPORTIENDA      40027
#define ID_CLIENTES_HISTORIAL           40028
#define ID_COMPRAS_ELIMINAR             40029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         40030
#define _APS_NEXT_CONTROL_VALUE         1198
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
